// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-05-02 16:05:42.622975929 +0800 CST m=+0.062204451

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a gin-api server Petstore server.",
        "title": "Gin API",
        "contact": {
            "name": "API Support",
            "url": "http://www.simonblog.cn",
            "email": "simon_yang@aliyun.com"
        },
        "license": {},
        "version": "1.0"
    },
    "paths": {
        "/users/captcha/{mobile}": {
            "get": {
                "description": "获取图片验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "获取图片验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mobile",
                        "name": "mobile",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"succeed\":false,\"data\":{},\"errorCode\":100002,\"errorMessage\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/login": {
            "post": {
                "description": "密码登录，验证码登录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mobile",
                        "name": "mobile",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Code",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"succeed\":false,\"data\":{},\"errorCode\":100002,\"errorMessage\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/register": {
            "post": {
                "description": "新用户注册",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mobile",
                        "name": "mobile",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Password",
                        "name": "password",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Code",
                        "name": "code",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"succeed\":false,\"data\":{},\"errorCode\":100002,\"errorMessage\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/vcode/{mobile}": {
            "get": {
                "description": "发送短信验证码",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "发送短信验证码",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Mobile",
                        "name": "mobile",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Captcha",
                        "name": "captcha",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"succeed\":false,\"data\":{},\"errorCode\":100002,\"errorMessage\":\"请求参数错误\"}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
